nelmio_api_doc:
    documentation:
        info:
            title: GoLocal
            description: Backend for GoLocal application
            version: 0.90.2

    areas: # to filter documented areas
        default:
            path_patterns: [ ^/api ]
        location:
            path_patterns: [ ^/api ]
    models:
        names:
            - { alias: LocationController,        type: App\Entity\Location }
