App\Entity\Client:
  attributes:
    id:
      groups: ['client']
    name:
      groups: [ 'client' ]
    surname:
      groups: [ 'client' ]
    email:
      groups: [ 'client' ]
    nick:
      groups: [ 'client' ]
    avatar:
      groups: [ 'client' ]
    uid_firebase:
      groups: [ 'client' ]