App\Entity\TypePost:
  attributes:
    id:
      groups: ['comentary']
    shop_comentary_related_id:
      groups: [ 'comentary' ]
    client_related_id:
      groups: [ 'comentary' ]
    content_comentary:
      groups: [ 'comentary' ]
