App\Entity\Location:
  attributes:
    id:
      groups : ['location']
    latitude:
      groups : ['location']
    longitude:
      groups : ['location']
    address:
      groups : ['location']
    id_google:
      groups : ['location']