App\Entity\ShopData:
  attributes:
    id:
      groups: ['shopData']
    phone:
      groups: ['shopData']
    isWhatsaap:
      groups: ['shopData']
    description:
      groups: ['shopData']
    image:
      groups: ['shopData']
    rate_average:
      groups: ['shopData']
    shop:
      groups: ['shopData']
